// === BETTER ERRORS UPDATE ==
// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see https://docs.c9.io/custom_runners.html
{
   "cmd": [
     "bash",
     "--login",
     "-c",
     "TRUSTED_IP=108.36.150.74 rails server -p $port -b $ip $args"
  ],
  "working_dir": "$project_path",
  "info": "Your code is running at \\033[01;34m$url\\033[00m.\n\\033[01;31m",
  "selector": "source.ru"
}